export const MAP_CHANGE = 'carta/Quest/MAP_CHANGE'

export const TYPE_CLICK = 'carta/Quest/TYPE_CLICK'
export const TYPE_ANYTHING_CLICK = 'carta/Quest/TYPE_ANYTHING_CLICK'

export const DESCRIPTIVE_CLICK = 'carta/Quest/DESCRIPTIVE_CLICK'
export const DESCRIPTIVE_STAR_CLICK = 'carta/Quest/DESCRIPTIVE_STAR_CLICK'
export const DESCRIPTIVE_ANYTHING_CLICK = 'carta/Quest/DESCRIPTIVE_ANYTHING_CLICK'

export const UPDATE_VISIBILITY = 'carta/Quest/UPDATE_VISIBILITY'

export const SET_DEFAULT_QUEST = 'carta/Quest/SET_DEFAULT_QUEST'

export const QUEST_ADD = 'carta/Quest/QUEST_ADD'
export const QUEST_SELECT = 'cara/Quest/QUEST_SELECT'
export const QUEST_REMOVE = 'carta/Quest/QUEST_REMOVE'

export const GET_QUESTINFO_REQUEST = 'carta/Quest/GET_QUESTINFO_REQUEST'
export const GET_QUESTINFO_SUCCESS = 'carta/Quest/GET_QUESTINFO_SUCCESS'
export const GET_QUESTINFO_FAIL = 'carta/Quest/GET_QUESTINFO_FAIL'

export const GET_RECOMMENDATION_REQUEST = 'carta/Quest/GET_RECOMMENDATION_REQUEST'
export const GET_RECOMMENDATION_SUCCESS = 'carta/Quest/GET_RECOMMENDATION_SUCCESS'
export const GET_RECOMMENDATION_FAIL = 'carta/Quest/GET_RECOMMENDATION_FAIL'

export const GET_BROCHURE_REQUEST = 'carta/Quest/GET_BROCHURE_REQUEST'
export const GET_BROCHURE_SUCCESS = 'carta/Quest/GET_BROCHURE_SUCCESS'
export const GET_BROCHURE_FAIL = 'carta/Quest/GET_BROCHURE_FAIL'
