export const FETCH_COMMUNITYINFO_REQUEST = 'carta/Home/FETCH_COMMUNITYINFO_REQUEST'
export const FETCH_COMMUNITYINFO_SUCCESS = 'carta/Home/FETCH_COMMUNITYINFO_SUCCESS'
export const FETCH_COMMUNITYINFO_FAIL = 'carta/Home/FETCH_COMMUNITYINFO_FAIL'

export const API_BASE_URL = process.env.API_BASE_URL
