export const CREATE_POST_REQUEST = 'carta/Home/CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'carta/Home/CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'carta/Home/CREATE_POST_FAIL'

export const LIST_POST_REQUEST = 'carta/Home/LIST_POST_REQUEST'
export const LIST_POST_SUCCESS = 'carta/Home/LIST_POST_SUCCESS'
export const LIST_POST_FAIL = 'carta/Home/LIST_POST_FAIL'

export const UPDATE_POST_REQUEST = 'carta/Home/UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'carta/Home/UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'carta/Home/UPDATE_POST_FAIL'

export const DELETE_POST_REQUEST = 'carta/Home/DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'carta/Home/DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'carta/Home/DELETE_POST_FAIL'

export const LIST_SUGGESTION_REQUEST = 'carta/Home/LIST_SUGGESTION_REQUEST'
export const LIST_SUGGESTION_SUCCESS = 'carta/Home/LIST_SUGGESTION_SUCCESS'
export const LIST_SUGGESTION_FAIL = 'carta/Home/LIST_SUGGESTION_FAIL'
