export const FETCH_COMMUNITYINFO_REQUEST = 'carta/Home/FETCH_COMMUNITYINFO_REQUEST'
export const FETCH_COMMUNITYINFO_SUCCESS = 'carta/Home/FETCH_COMMUNITYINFO_SUCCESS'
export const FETCH_COMMUNITYINFO_FAIL = 'carta/Home/FETCH_COMMUNITYINFO_FAIL'

export const UPDATE_POST_REQUEST = 'carta/Home/UPDATE_POST_REQUEST'
export const UPDATE_POST_SUCCESS = 'carta/Home/UPDATE_POST_SUCCESS'
export const UPDATE_POST_FAIL = 'carta/Home/UPDATE_POST_FAIL'

export const DELETE_POST_REQUEST = 'carta/Home/DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'carta/Home/DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'carta/Home/DELETE_POST_FAIL'
